[mypy]
python_version = 3.9
strict = False
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True

[mypy-pipeline_inspector.reports.html_report]
disable_error_code = var-annotated

[mypy-py_cerebro.*]
ignore_missing_imports = True

[mypy-pycerebro.*]
ignore_missing_imports = True
