"""Thinkbox Deadline 10 on-prem integration for Pipeline Inspector."""

from pipeline_inspector.integrations.deadline.analytics import (
    FarmAnalyticsMetrics,
    FarmAnalyticsReport,
    FarmJobTotals,
    collect_farm_analytics,
    farm_analytics_to_dict,
    format_farm_analytics_summary,
)
from pipeline_inspector.integrations.deadline.client import (
    DeadlineClient,
    DeadlineClientError,
    DeadlineResponse,
    HttpRequest,
    HttpTransport,
    default_http_transport,
)
from pipeline_inspector.integrations.deadline.config import (
    DEFAULT_PROFILE_ID,
    DeadlineConfig,
)
from pipeline_inspector.integrations.deadline.eligibility import (
    FarmEligibilityDecision,
    FarmEligibilityResult,
    FarmSceneState,
    FarmValidationResult,
    evaluate_farm_submit_eligibility,
)
from pipeline_inspector.integrations.deadline.preflight import (
    PREFLIGHT_ERROR,
    SUBMISSION_ALLOWED,
    SUBMISSION_BLOCKED,
    VALIDATOR_CONFIG_ERROR,
    VALIDATOR_DEADLINE_BLOCK,
    VALIDATOR_OK,
    VALIDATOR_PUBLISH_BLOCK,
    VALIDATOR_RUNTIME_ERROR,
    DeadlinePreflightResult,
    blocked_message,
    build_validator_command,
    run_deadline_preflight,
)
from pipeline_inspector.integrations.deadline.submit import (
    COMMAND_SCRIPT_PLUGIN,
    MAYA_BATCH_PLUGIN,
    DeadlineSubmitError,
    PipelineInspectorValidationJobResult,
    build_command_script_job,
    build_command_script_line,
    build_maya_batch_script_job,
    submit_pipeline_inspector_validation_job,
    write_command_script_file,
)

__all__ = [
    "COMMAND_SCRIPT_PLUGIN",
    "DEFAULT_PROFILE_ID",
    "DeadlineClient",
    "DeadlineClientError",
    "DeadlineConfig",
    "DeadlinePreflightResult",
    "DeadlineResponse",
    "DeadlineSubmitError",
    "FarmAnalyticsMetrics",
    "FarmAnalyticsReport",
    "FarmEligibilityDecision",
    "FarmEligibilityResult",
    "FarmJobTotals",
    "FarmSceneState",
    "FarmValidationResult",
    "HttpRequest",
    "HttpTransport",
    "MAYA_BATCH_PLUGIN",
    "PREFLIGHT_ERROR",
    "SUBMISSION_ALLOWED",
    "SUBMISSION_BLOCKED",
    "PipelineInspectorValidationJobResult",
    "VALIDATOR_CONFIG_ERROR",
    "VALIDATOR_DEADLINE_BLOCK",
    "VALIDATOR_OK",
    "VALIDATOR_PUBLISH_BLOCK",
    "VALIDATOR_RUNTIME_ERROR",
    "blocked_message",
    "build_command_script_job",
    "build_command_script_line",
    "build_maya_batch_script_job",
    "build_validator_command",
    "collect_farm_analytics",
    "default_http_transport",
    "evaluate_farm_submit_eligibility",
    "farm_analytics_to_dict",
    "format_farm_analytics_summary",
    "run_deadline_preflight",
    "submit_pipeline_inspector_validation_job",
    "write_command_script_file",
]
