"""Core data contracts and validation primitives."""

from shader_health.core.models import (
    SNAPSHOT_SCHEMA_VERSION,
    ConnectionSnapshot,
    FileDependencySnapshot,
    GraphSnapshot,
    ImageInfo,
    MaterialSnapshot,
    NodeSnapshot,
    ReferenceSnapshot,
    ShadingEngineSnapshot,
)
from shader_health.core.rule_loader import (
    ProfileDefinition,
    RuleLoadError,
    RuleOverride,
    apply_profile_overrides,
    build_rule_search_paths,
    load_profile,
    load_rule_file,
    load_rule_stack,
    load_rules_from_path,
)
from shader_health.core.rule_schema import (
    RULE_SCHEMA_VERSION,
    RuleCheck,
    RuleDefinition,
    RuleFix,
    RuleMatch,
    RulePolicy,
    RuleSchemaError,
)

__all__ = [
    "RULE_SCHEMA_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "ConnectionSnapshot",
    "FileDependencySnapshot",
    "GraphSnapshot",
    "ImageInfo",
    "MaterialSnapshot",
    "NodeSnapshot",
    "ProfileDefinition",
    "ReferenceSnapshot",
    "RuleCheck",
    "RuleDefinition",
    "RuleFix",
    "RuleLoadError",
    "RuleMatch",
    "RuleOverride",
    "RulePolicy",
    "RuleSchemaError",
    "ShadingEngineSnapshot",
    "apply_profile_overrides",
    "build_rule_search_paths",
    "load_profile",
    "load_rule_file",
    "load_rule_stack",
    "load_rules_from_path",
]
