"""Core data contracts and validation primitives."""

from shader_health.core.fix_plan import (
    FixAction,
    FixPlan,
    build_fix_plan,
)
from shader_health.core.models import (
    SNAPSHOT_SCHEMA_VERSION,
    ConnectionSnapshot,
    FileDependencySnapshot,
    GraphSnapshot,
    ImageInfo,
    MaterialSnapshot,
    NodeSnapshot,
    ReferenceSnapshot,
    ShadingEngineSnapshot,
)
from shader_health.core.rule_loader import (
    ProfileDefinition,
    RuleLoadError,
    RuleOverride,
    apply_profile_overrides,
    build_rule_search_paths,
    load_profile,
    load_rule_file,
    load_rule_stack,
    load_rules_from_path,
)
from shader_health.core.rule_schema import (
    RESULT_STATUSES,
    RULE_SCHEMA_VERSION,
    RuleCheck,
    RuleDefinition,
    RuleFix,
    RuleMatch,
    RulePolicy,
    RuleResult,
    RuleSchemaError,
    ValidationEngine,
    ValidationSummary,
    summarize_results,
)
from shader_health.core.scoring import (
    HealthScore,
    compute_health_score,
)
from shader_health.core.waivers import (
    WAIVED_STATUS,
    WAIVER_SCHEMA_VERSION,
    WaiverRecord,
    WaiverSidecar,
    apply_waivers,
    create_waiver_from_result,
    load_waiver_sidecar,
    write_waiver_sidecar,
)

__all__ = [
    "RESULT_STATUSES",
    "RULE_SCHEMA_VERSION",
    "SNAPSHOT_SCHEMA_VERSION",
    "WAIVED_STATUS",
    "WAIVER_SCHEMA_VERSION",
    "ConnectionSnapshot",
    "FileDependencySnapshot",
    "FixAction",
    "FixPlan",
    "GraphSnapshot",
    "HealthScore",
    "ImageInfo",
    "MaterialSnapshot",
    "NodeSnapshot",
    "ProfileDefinition",
    "ReferenceSnapshot",
    "RuleCheck",
    "RuleDefinition",
    "RuleFix",
    "RuleLoadError",
    "RuleMatch",
    "RuleOverride",
    "RulePolicy",
    "RuleResult",
    "RuleSchemaError",
    "ShadingEngineSnapshot",
    "ValidationEngine",
    "ValidationSummary",
    "WaiverRecord",
    "WaiverSidecar",
    "apply_profile_overrides",
    "apply_waivers",
    "build_fix_plan",
    "build_rule_search_paths",
    "compute_health_score",
    "create_waiver_from_result",
    "load_profile",
    "load_rule_file",
    "load_rule_stack",
    "load_rules_from_path",
    "load_waiver_sidecar",
    "summarize_results",
    "write_waiver_sidecar",
]
